# Generated by Django 3.0.8 on 2020-07-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_funding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funding',
        ),
        migrations.AddField(
            model_name='post',
            name='totalfund',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
