# Generated by Django 3.0.8 on 2020-07-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200721_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('quantity', models.IntegerField(default=1)),
                ('phone', models.IntegerField(max_length=128)),
                ('message_store', models.CharField(max_length=256)),
            ],
        ),
    ]
