# Generated by Django 3.0.8 on 2020-07-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_order_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='purchasetype',
            field=models.CharField(choices=[('T1', 'Type1')], max_length=2, null=True),
        ),
    ]
