# Generated by Django 3.0.8 on 2020-07-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200728_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
