# Generated by Django 3.0.8 on 2020-07-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchasetype',
            field=models.CharField(choices=[('T1', 'Type1')], max_length=60, null=True),
        ),
    ]
