# Generated by Django 3.0.8 on 2020-07-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200728_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchasetype',
        ),
        migrations.AddField(
            model_name='order',
            name='option',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='purchasetype',
            field=models.CharField(choices=[('T1', 'Type1 $7,800'), ('T2', 'Type2 $10,000')], max_length=60, null=True),
        ),
    ]
