# Generated by Django 3.0.8 on 2020-07-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_order_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.IntegerField(max_length=60)),
                ('call', models.IntegerField(max_length=60)),
                ('sum_call', models.IntegerField(max_length=60)),
                ('stat_rate', models.IntegerField(max_length=60)),
            ],
        ),
    ]
