# Generated by Django 3.0.8 on 2020-07-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='call',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stat_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sum_call',
            field=models.IntegerField(),
        ),
    ]
