# Generated by Django 3.0.8 on 2020-07-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200728_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='call',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stat_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sum_call',
            field=models.FloatField(),
        ),
    ]
