# Generated by Django 3.0.8 on 2020-07-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_post_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='purchasetype',
        ),
    ]
